Repository TDevUIT/PirateSocial, pull requests merged in 2024-09, with the labels that each got.

#9 feat: add options sideber, wallet, Profile, saved message, invite friend, account sett ing, wallet
  client/src/app/(auth)/forgot/page.tsx
  client/src/app/(auth)/layout.tsx
  client/src/app/(auth)/sign-in/page.tsx
  client/src/app/(auth)/sign-up/page.tsx
  client/src/app/layout.tsx
  client/src/app/messages/_components/inviteFriend.tsx
  client/src/app/messages/_components/myProfile.tsx
  client/src/app/messages/_components/profileSidebar.tsx
  client/src/app/messages/_components/savedMessage.tsx
  client/src/app/messages/_components/settingsAccount.tsx
  client/src/app/messages/_components/walletPage.tsx
  client/src/app/page.tsx
  client/src/components/ToastContainer.tsx
  client/src/components/home/callToAction.tsx
  client/src/components/home/features.tsx
  client/src/components/home/footer.tsx
  client/src/components/home/heroSection.tsx
  client/src/context/ToastContext.tsx
  client/src/context/control.tsx
Labels: feat

#15 feat: add reviews, loading component
  client/src/app/(auth)/layout.tsx
  client/src/app/(auth)/sign-in/page.tsx
  client/src/app/(auth)/sign-up/page.tsx
  client/src/app/globals.css
  client/src/app/layout.tsx
  client/src/app/loading.tsx
  client/src/app/messages/layout.tsx
  client/src/app/page.tsx
  client/src/components/home/reviews.tsx
  client/src/components/ui/marquee.tsx
  client/tailwind.config.ts
Labels: feat

#16 fix: update landing page
  client/next.config.mjs
  client/src/app/error.tsx
  client/src/app/globals.css
  client/src/app/not-found.tsx
  client/src/app/page.tsx
  client/src/components/ButtonSupport.tsx
  client/src/components/home/heroSection.tsx
  client/src/components/navbar.tsx
Labels: fix

#27 fix: add realtime chat
  Server/package.json
  Server/src/Gateway/chat.gateway.ts
  Server/src/chat/chat.service.ts
  Server/src/room/room.service.ts
  client/src/app/messages/[id]/page.tsx
Labels: fix

#28 fix: refix body frame
  Server/src/Gateway/chat.gateway.ts
  Server/src/chat/chat.service.ts
  Server/src/room/room.service.ts
Labels: fix

#29 feat: update model db ver 10/9/2024 messageBox
  Server/model.txt
Labels: feat

#31 feat: update model new ver
  Server/package-lock.json
  Server/prisma/migrations/20240913144249_init/migration.sql
  Server/prisma/migrations/20240913144403_init/migration.sql
  Server/prisma/migrations/20240913145241_init/migration.sql
  Server/prisma/migrations/20240915065032_init/migration.sql
  Server/prisma/migrations/20240915082147_init/migration.sql
  Server/prisma/schema.prisma
  Server/src/Gateway/chat.gateway.ts
  Server/src/chat/chat.controller.ts
  Server/yarn.lock
Labels: feat

#32 feat: show profile picture in messages
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/epic.md
  .github/ISSUE_TEMPLATE/task-frontend.md
  .github/ISSUE_TEMPLATE/task.md
  .github/pull_request_template.md
  Server/package.json
  Server/src/Gateway/chat.gateway.ts
  Server/src/chat/chat.service.ts
  client/src/app/messages/[id]/page.tsx
  client/src/types.ts
Labels: enhancement, feat

#34 feat: update api get data room
  Server/src/Gateway/chat.gateway.ts
  Server/src/room/room.controller.ts
  Server/src/room/room.service.ts
  Server/src/user/user.controller.ts
  Server/src/user/user.service.ts
Labels: feat
